[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "guillerc10",email = "guillermocaceres164@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
    "django (>=6.1.1,<7.0.0)",
    "djangorestframework (>=3.18.0,<4.0.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)",
    "requests (>=2.34.2,<3.0.0)",
    "django-cors-headers (>=4.9.0,<5.0.0)",
    "numpy (>=2.5.2,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
