# Generated by Django 6.1.1 on 2026-09-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_partida_queue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='lp_change',
            field=models.IntegerField(default=0),
        ),
    ]
